# 1. Usa una imagen base oficial y ligera de Python (Versión 3.11 recomendada)
FROM python:3.11-slim

# 2. Variables de entorno globales
# PYTHONDONTWRITEBYTECODE: Evita que python cree los archivos basura de caché (.pyc)
# PYTHONUNBUFFERED: Permite que los logs salgan directo en la consola de AWS sin demoras
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# 3. Establece la carpeta principal de trabajo DENTRO de la máquina / contenedor
WORKDIR /app

# 4. Instalar utilidades del sistema base por si asyncpg o passlib requieren compilar
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# 5. Copia SOLAMENTE el archivo de dependencias primero 
# (Truco para acelerar Docker: si solo cambias el código de FastAPI, Docker no volverá a instalar librerías)
COPY requirements.txt .

# 6. Instala las dependencias usando pip
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# 7. Copia TODO el resto de tu código de backend (tu carpeta app/, alembic/, etc.)
COPY . .

# 8. Expone el puerto por el que FastAPI escuchará el tráfico en internet
EXPOSE 8000

# 9. El comando mágico que corre cuando el contenedor (o tu servidor en AWS) se enciende.
# app.main:app le dice a Uvicorn que busque la variable "app" dentro de la carpeta "app", archivo "main.py"
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
