"""add_deuda_comision

Revision ID: 3f5d33f21038
Revises: 41fa45efd0f2
Create Date: 2026-04-27 22:23:50.483921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5d33f21038'
down_revision: Union[str, Sequence[str], None] = '41fa45efd0f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('deuda_comision', sa.Float(), server_default='0.0', nullable=False, comment='Deuda acumulada de comisiones no pagadas (pagos en efectivo). Límite: 500 Bs.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'deuda_comision')
    # ### end Alembic commands ###
