"""add_fcm_token_stripe_fields_deuda_comision

Revision ID: 41fa45efd0f2
Revises: c3d4e5f6g7h8
Create Date: 2026-04-27 21:24:28.420253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fa45efd0f2'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # deuda_comision ya fue aplicado en la ejecución parcial anterior
    # op.add_column('admins', ...)

    # Crear el tipo ENUM para tipo_pago explícitamente
    tipo_pago_enum = sa.Enum('TARJETA', 'EFECTIVO', 'QR', name='tipo_pago')
    tipo_pago_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('pagos', sa.Column('tipo_pago', tipo_pago_enum, nullable=True))
    op.add_column('pagos', sa.Column('stripe_session_id', sa.String(length=300), nullable=True))
    op.add_column('pagos', sa.Column('stripe_payment_intent_id', sa.String(length=300), nullable=True))
    op.add_column('pagos', sa.Column('comprobante_url', sa.Text(), nullable=True))
    op.add_column('usuarios', sa.Column('fcm_token', sa.String(length=500), nullable=True, comment='Token FCM para push notifications'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fcm_token')
    op.drop_column('pagos', 'comprobante_url')
    op.drop_column('pagos', 'stripe_payment_intent_id')
    op.drop_column('pagos', 'stripe_session_id')
    op.drop_column('pagos', 'tipo_pago')
    op.drop_column('admins', 'deuda_comision')
    # ### end Alembic commands ###
