"""Add AuditableMixin

Revision ID: 43a8c5e31118
Revises: de04d65feb22
Create Date: 2026-04-08 23:50:34.321894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a8c5e31118'
down_revision: Union[str, Sequence[str], None] = 'de04d65feb22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('empleados', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('empleados', sa.Column('es_eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('empleados', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_empleados_es_eliminado'), 'empleados', ['es_eliminado'], unique=False)
    op.add_column('ordenes_trabajo', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('es_eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_ordenes_trabajo_es_eliminado'), 'ordenes_trabajo', ['es_eliminado'], unique=False)
    op.add_column('solicitudes_emergencia', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('solicitudes_emergencia', sa.Column('es_eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('solicitudes_emergencia', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_solicitudes_emergencia_es_eliminado'), 'solicitudes_emergencia', ['es_eliminado'], unique=False)
    op.add_column('sucursales', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sucursales', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sucursales', sa.Column('es_eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('sucursales', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sucursales_es_eliminado'), 'sucursales', ['es_eliminado'], unique=False)
    op.add_column('talleres', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('talleres', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('talleres', sa.Column('es_eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('talleres', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_talleres_es_eliminado'), 'talleres', ['es_eliminado'], unique=False)
    op.add_column('usuarios', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('es_eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('usuarios', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_usuarios_es_eliminado'), 'usuarios', ['es_eliminado'], unique=False)
    op.add_column('vehiculos', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vehiculos', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vehiculos', sa.Column('es_eliminado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('vehiculos', sa.Column('fecha_eliminacion', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_vehiculos_es_eliminado'), 'vehiculos', ['es_eliminado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculos_es_eliminado'), table_name='vehiculos')
    op.drop_column('vehiculos', 'fecha_eliminacion')
    op.drop_column('vehiculos', 'es_eliminado')
    op.drop_column('vehiculos', 'fecha_actualizacion')
    op.drop_column('vehiculos', 'fecha_creacion')
    op.drop_index(op.f('ix_usuarios_es_eliminado'), table_name='usuarios')
    op.drop_column('usuarios', 'fecha_eliminacion')
    op.drop_column('usuarios', 'es_eliminado')
    op.drop_column('usuarios', 'fecha_actualizacion')
    op.drop_index(op.f('ix_talleres_es_eliminado'), table_name='talleres')
    op.drop_column('talleres', 'fecha_eliminacion')
    op.drop_column('talleres', 'es_eliminado')
    op.drop_column('talleres', 'fecha_actualizacion')
    op.drop_column('talleres', 'fecha_creacion')
    op.drop_index(op.f('ix_sucursales_es_eliminado'), table_name='sucursales')
    op.drop_column('sucursales', 'fecha_eliminacion')
    op.drop_column('sucursales', 'es_eliminado')
    op.drop_column('sucursales', 'fecha_actualizacion')
    op.drop_column('sucursales', 'fecha_creacion')
    op.drop_index(op.f('ix_solicitudes_emergencia_es_eliminado'), table_name='solicitudes_emergencia')
    op.drop_column('solicitudes_emergencia', 'fecha_eliminacion')
    op.drop_column('solicitudes_emergencia', 'es_eliminado')
    op.drop_column('solicitudes_emergencia', 'fecha_actualizacion')
    op.drop_index(op.f('ix_ordenes_trabajo_es_eliminado'), table_name='ordenes_trabajo')
    op.drop_column('ordenes_trabajo', 'fecha_eliminacion')
    op.drop_column('ordenes_trabajo', 'es_eliminado')
    op.drop_column('ordenes_trabajo', 'fecha_actualizacion')
    op.drop_column('ordenes_trabajo', 'fecha_creacion')
    op.drop_index(op.f('ix_empleados_es_eliminado'), table_name='empleados')
    op.drop_column('empleados', 'fecha_eliminacion')
    op.drop_column('empleados', 'es_eliminado')
    op.drop_column('empleados', 'fecha_actualizacion')
    op.drop_column('empleados', 'fecha_creacion')
    # ### end Alembic commands ###
