"""Update UsuarioPerfil fields for profile

Revision ID: 55e3569ea840
Revises: b64af17fbb55
Create Date: 2026-04-10 22:49:43.573298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e3569ea840'
down_revision: Union[str, Sequence[str], None] = 'b64af17fbb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_perfiles', sa.Column('apellido_paterno', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('usuario_perfiles', sa.Column('apellido_materno', sa.String(length=100), nullable=True))
    op.add_column('usuario_perfiles', sa.Column('foto_perfil', sa.Text(), nullable=True))
    op.drop_column('usuario_perfiles', 'apellidos')
    op.drop_column('usuario_perfiles', 'foto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario_perfiles', sa.Column('foto', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('usuario_perfiles', sa.Column('apellidos', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('usuario_perfiles', 'foto_perfil')
    op.drop_column('usuario_perfiles', 'apellido_materno')
    op.drop_column('usuario_perfiles', 'apellido_paterno')
    # ### end Alembic commands ###
