"""Add qr_imagen_url to admin

Revision ID: af1c2294a9d1
Revises: 3f5d33f21038
Create Date: 2026-04-28 16:11:18.480742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1c2294a9d1'
down_revision: Union[str, Sequence[str], None] = '3f5d33f21038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('qr_imagen_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'qr_imagen_url')
    # ### end Alembic commands ###
