"""Update EstadoSolicitud and EstadoAsignacion, add motivo_rechazo to asignacion

Revision ID: af4b88c9ec6a
Revises: 2b21435fcefa
Create Date: 2026-05-29 01:08:11.172922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4b88c9ec6a'
down_revision: Union[str, Sequence[str], None] = '2b21435fcefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asignaciones', sa.Column('motivo_rechazo', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    
    # Add new values to PostgreSQL ENUMs
    # Note: PostgreSQL does not allow dropping enum values easily, so we just add the new ones.
    # The old values (PENDIENTE_SELECCION_CLIENTE, etc) will remain in the DB type but unused.
    op.execute("ALTER TYPE estado_solicitud ADD VALUE IF NOT EXISTS 'OFERTA_ACEPTADA'")
    op.execute("ALTER TYPE estado_solicitud ADD VALUE IF NOT EXISTS 'ESPERANDO_CONFIRMACION_MECANICO'")
    op.execute("ALTER TYPE estado_solicitud ADD VALUE IF NOT EXISTS 'EN_CAMINO'")
    op.execute("ALTER TYPE estado_solicitud ADD VALUE IF NOT EXISTS 'EN_SITIO'")
    op.execute("ALTER TYPE estado_solicitud ADD VALUE IF NOT EXISTS 'FINALIZADO'")

    op.execute("ALTER TYPE estado_asignacion ADD VALUE IF NOT EXISTS 'EN_CAMINO'")
    op.execute("ALTER TYPE estado_asignacion ADD VALUE IF NOT EXISTS 'EN_SITIO'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asignaciones', 'motivo_rechazo')
    # ### end Alembic commands ###
