"""add_ubicacion_postgis_to_empleados

Revision ID: b64af17fbb55
Revises: 43a8c5e31118
Create Date: 2026-04-10 21:43:03.357401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b64af17fbb55'
down_revision: Union[str, Sequence[str], None] = '43a8c5e31118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # op.create_index('idx_empleados_ubicacion', 'empleados', ['ubicacion'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_empleados_ubicacion', table_name='empleados', postgresql_using='gist')
    op.drop_column('empleados', 'ubicacion')
    # ### end Alembic commands ###
