"""Marketplace de pujas

Revision ID: f49785cb64d9
Revises: af1c2294a9d1
Create Date: 2026-05-26 14:07:51.718161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49785cb64d9'
down_revision: Union[str, Sequence[str], None] = 'af1c2294a9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pujas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio_estimado', sa.Float(), nullable=False),
    sa.Column('tiempo_llegada_minutos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ACEPTADA', 'RECHAZADA', name='estado_puja', create_constraint=True), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_emergencia.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pujas_id'), 'pujas', ['id'], unique=False)
    op.create_index(op.f('ix_pujas_solicitud_id'), 'pujas', ['solicitud_id'], unique=False)
    op.alter_column('admins', 'deuda_comision',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Deuda acumulada de comisiones no pagadas (pagos en efectivo). Límite: 150 Bs.',
               existing_comment='Deuda acumulada de comisiones no pagadas (pagos en efectivo). Límite: 500 Bs.',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'deuda_comision',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Deuda acumulada de comisiones no pagadas (pagos en efectivo). Límite: 500 Bs.',
               existing_comment='Deuda acumulada de comisiones no pagadas (pagos en efectivo). Límite: 150 Bs.',
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('ix_pujas_solicitud_id'), table_name='pujas')
    op.drop_index(op.f('ix_pujas_id'), table_name='pujas')
    op.drop_table('pujas')
    # ### end Alembic commands ###
